server{
    listen 3000;

    location /healthz/ {
        add_header Content-Type text/plain;
        return 200 'ya zhivoy frontend\n';     
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }


}